### ISSUE TITLE
Hangs on TYPE I

### ISSUE THREAD

**Issue by trslater** [git-ftp/git-ftp#122]
I'm trying to do a git ftp init and am using the -vv to see why nothing happens. It connects find, traverses the directories fine, but then hangs on "TYPE I". Any ideas?

**Comment by lithstud** [comment]
Hey, do you know any idea why this could happen? We have same issue, unfortunately, changing host is not the option here. 

@resmo @TristanSlater

**Comment by TristanSlater** [comment]
I have no idea. I never figured it out. I ended up scraping that whole workflow, because it was too problematic / unreliable, and my knowledge of linux / servers / apache / mt isn't good enough to figure out what was wrong. I ended up using dploy.io, which I really loved, but was too expensive (for me) for a long term solution, so I'm back to manual FTP :( Using Transmit's sync function and getting good with keyboard shortcuts, you can get a pretty similar experience.

**Comment by mkllnk** [comment]
@lithstud Do you say you have that problem only on Ubuntu? And it hangs somewhere during the upload? Which version do you use?

**Comment by lithstud** [comment]
@mkllnk Yes that is correct, it's a vagrant box running on mac to be honest, but replicates our live servers 100%. (the server that this app would run on). It runs just perfectly on my mac (latest el capitan)

Ubuntu version is 14.04
vagrant@xxx:~$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
vagrant@xxx:~$ git-ftp --version
git-ftp version 1.2.0

I also must note, that usually it is stuck on TYPE I, but now instead of adding options on runtime, I have added all the details to git config, this time it is stuck on TYPE A. Really confusing. 

Is there any other details that you think would help? Also, I do have root access to the server that I'm trying FTP to, it's a shared hosting owned by us so I can provide any detail, altough my knowledge with it is limited so you would need to tell me what details can help.

**Comment by lithstud** [comment]
@mkllnk 
Hi again,
So I have found a workaround, and it's basically what you @TristanSlater said, it works with disabling EPSV. I also had to rebuild curl on the server, to include libssh2. I always thought that it is enabled but apparently not!

Anyways, thanks for answering!
