### ISSUE TITLE
RFC: get clean workspace before push

### ISSUE THREAD

**Issue by resmo** [git-ftp/git-ftp#164]
There are a few use cases where a clean workspace or a "clean clone" to a tmp dir would help prevent race conditions and failures e.g. someone changes files while uploading.

basically this would be:

```
cp -rp . /tmp/<head-commit-id>/
cd  /tmp/<head-commit-id>/
```

This would also allow us to define a commit instead of HEAD

```
cp -rp . /tmp/<source-commit-id>/
cd  /tmp/<head-commit-id>/
git reset --hard <source-commit-id>
```

**Comment by resmo** [comment]
@mkllnk any concerns?

**Comment by mkllnk** [comment]
I thought about that as well. It would be good if we could work with the repository data instead of the actual files in the working tree. But we need the files for the transfer (unless we upload each file individually and feed curl's stdin).

Cloning a whole repository can be quite expensive. But we can assemble the file lists without changing the working tree. We could store temporary files in .git/git-ftp/ or use `mktemp`. Then we can export the files to upload with `git archive` instead of clone. Maybe the upload command can be simplified with a wildcard.

My draft for now would be:

* Assemble file lists (upload and delete) as we do now.
* Create a temp directory with `mktemp`.
* Copy files to upload into the temp dir with `git archive`.
* Delete remote files as we do now.
* Upload all files in the temp dir.

As next step I would change the location of all the -tmp-files like .git-ftp-ignore-tmp to the temp directory or .git/git-ftp/.

What do you think?

**Comment by resmo** [comment]
You are right, cloning the whole repo is expensive, I also realise that git config won't be stored as well as untracked files (listed in .git-ftp-include). 

So the only missing point in your draft IMHO:

* ...
* Copy files in .git-ftp-include into the temp dir as well
* ...

Your approach looks like the way to go.

About the -tmp-files, I vote for .git/git-ftp/,

I created a branch `/feature/clean-workspace-164` for the work.
