### ISSUE TITLE
Constantly gets  "fatal: Can't access remote 'ftp://www.myserver.com/'., exiting..."

### ISSUE THREAD

**Issue by bastiantowers** [git-ftp/git-ftp#204]
Constantly gets  "fatal: Can't access remote 'ftp://www.myserver.com/'., exiting..." with whatever address I tried.

Using this command on GitBash on Windows 8.1:
git ftp push -u user -P ftp://myserver.com
works perfect. It prompts a request for my password and everything works as expected.

Using the exactly same command on a terminal on MacOS X Yosemite 10.10, doesn't work, and I always receive this "Can't access" error on whatever address I try.

I've tried to init again with git ftp init, I've tried with -D to retrieve .git-ftp.log from server. Nothing worked.
It works perfect on GitBash on Win8.1, but I couldn't make it works on a recent installation on Mac.

I don't know what the problem is. Maybe someone can help me.

Thanks!!!

**Comment by rockiger** [comment]
I get the same error on arch linux.

**Comment by bastiantowers** [comment]
I want to make it clear:
I've been working with this repository before, in Git Bash on Win8.1. I've been using git-ftp to push all my work to the ftp server and I didn't have any problem with it.
The problem is that I can't make it work in my Mac. The commands that perfectly works in Win8.1, doesn't work in Mac.

Maybe some idea would be useful, considering that git-ftp is commonly tested on Linux, I can help with the tests on Windows and Mac.

**Comment by bastiantowers** [comment]
I made it work following the guide in this post: https://codingsomething.wordpress.com/2013/04/03/git-ftp/

Maybe, there are some dependencies that are not correctly installed, and installing git-ftp with MacPorts, this is corrected. Here you can read some documentation about MacPorts: http://guide.macports.org/#introduction

I would suggest to include this information in the documentation for Mac Users.

**Comment by bastiantowers** [comment]
It would be nice too if we put in the documentation that we need to init the git-ftp for the same repo if we deploy to ftp from differents computers. For example, you got a repository in Windows and Mac, and you want to develop and use git-ftp to deploy your work to your ftp server, you need to use "git-ftp init" in both machines.

**Comment by heldrida** [comment]
Same error in Ubuntu : X

**Comment by heldrida** [comment]
Actually, after  following the post suggested by @bastiantowers, by setting the configuration parameters for username, ftp protocol/url/port/path, etc. It's working!

Thank you!

**Comment by mkllnk** [comment]
@bastiantowers Thanks a lot for reporting and solving your issue. But it looks like we haven't found the actual cause of the problem yet. Did setting all credentials with git-config solve your problem or was it the dependency installation of mac port?

`git ftp init`: Initialising once should be enough. What happens if you don't initialise the second repository? Any error?

**Comment by heldrida** [comment]
The same just happened at my work computer running OSX Yosemite 10.10.3. The solution was to set the git-ftp configuration parameters as @bastiantowers described https://codingsomething.wordpress.com/2013/04/03/git-ftp/

**Comment by Stolzenhain** [comment]
Same behaviour here – new repo, installed via Homebew, init always breaks with error `Can't access remote 'ftp://`while providing server, username, password via 'git config git-ftp.' works. 
I wouldn't mind putting up server and user in the config, but leaving passwords in the git credentials bugs me a bit.

**Comment by bastiantowers** [comment]
@mkllnk I've solved the issue installing Git-Ftp with MacPorts.
Its working fine now.
Usually on Win8.1, I just use git-ftp init and everything goes fine (using GitBash).

Is there anything in particular that you want me to try??
I can test on Win 7, 8 or Mac if you needed it to...

Thanks!

**Comment by mkllnk** [comment]
@bastiantowers That's very cool. You can reproduce the problem, right? And it worked in the past, right?

The first thing would be to run it with `-vv` to enable verbose output. There you can see which command line arguments work and which don't. It looks like it's not taking the arguments correctly.

Then, if it worked in the past, you could try a `git bisect` on the git-ftp repository to find the commit that broke it on OSX. Do you know how MacPorts is installing git-ftp? Do they have some release on their server? Or is it taking a certain release from GitHub?
It would be interesting if the difference of MacPorts is a different git-ftp version or a different environment on dependencies.

That should help to narrow it down. After that, I hope we have some code snippets we can test on OSX so that we know what works and what doesn't.

**Comment by bastiantowers** [comment]
@mklink Thanks for your answers!

There was no commit that broke the repo on my Mac. Git-Ftp never worked in Mac with the installation with homebrew proposed in the README. It worked following the guide that I've posted before. I mean, it worked when I made the installation with MacPorts.

The version on my Mac is git-ftp version 0.8.1

The behavior is unstable in Mac. I've been throwing some commands with the -vv and I found some strange logs. Commonly, I think there is a problem on passing the password over the arguments of the commands. I think that the main problem is that git-ftp never reach the server. For example, look this:

![captura de pantalla 2015-09-26 a las 9 27 06](https://cloud.githubusercontent.com/assets/7130095/10117552/9d238466-6431-11e5-9a15-56050c7840ee.jpg)

It didn't get access to the password passed in the arguments, and it even tries to connect without this password.

Let me know your commentas about it.

Thanks!

**Comment by mkllnk** [comment]
Nice screenshot. I noticed that you tried to set the password with `-P` but it is `-p`. Try that.

**Comment by bastiantowers** [comment]
Sorry, I´ve been testing a lot, but I've put the wrong screenshot.

It worked with the -p:
![captura de pantalla 2015-09-26 a las 21 07 52](https://cloud.githubusercontent.com/assets/7130095/10120517/d43af346-6493-11e5-99fd-ab16bdf70217.png)

 but when using -P, it never prompts the password request...

![captura de pantalla 2015-09-26 a las 21 09 51](https://cloud.githubusercontent.com/assets/7130095/10120526/579f61ae-6494-11e5-9a1c-31a42d72f217.png)

See things like:
"egrep: repetition-operator operand invalid"
"Sat Sep 26 21:09:34 ART 2015: Added missing trailing / in path.
Sat Sep 26 21:09:34 ART 2015: Path is 'public_html/path//'."
I perceive an erratic behavior in such things... right? or am I doing somenthing wrong?

Thanks for your help! :)

**Comment by mkllnk** [comment]
There is no option `-P`. If you want to be prompted for a password, use `-p` without any argument.

We still have the invalid repetition operand. But I don't know which code is triggering that. These are all `egrep` calls in the source code of the version you are using:
```sh
egrep -q "/"
egrep -q "*/$"
egrep '^(ftp|sftp|ftps|ftpes)://.*'
egrep -q '^-'
```

You can test them with any string and see if they give you that error: `echo test | egrep -q "*/$"`

Actually, exactly that one was changed in newer versions. Because it doesn't make any sense to me. Now it is just `egrep -q "/$". Is it the one giving that error?
