### ISSUE TITLE
Tracking file permissions when uploading

### ISSUE THREAD

**Issue by livmackintosh** [git-ftp/git-ftp#220]
Hi there :)

Not sure if this is git-ftp or a git issue but I'm not sure I have the ability to track file permissions as things are uploaded. I have a few directories in my project that I don't want people to access publically (like dependencies and scripts) - is there a way for Git to to track file permissions or for git-ftp to recognise them?

Kind Regards,

Liv :smile_cat:

**Comment by mkllnk** [comment]
Hi!

Git does not store full file permissions. It just stores if a file is executable or not. Git-ftp can't change that.

Furthermore, the file permissions on the server depend on the server configuration. There is an FTP command to change file permissions. But since that command is not supported by all servers and Git doesn't provide the file permissions you need, it doesn't make sense to use it within Git-ftp.

You will need another way of setting file permissions and protecting your files.
