### ISSUE TITLE
Push and init command should trigger pre-push hook

### ISSUE THREAD

**Issue by adriandmitroca** [git-ftp/git-ftp#232]
As it says in title. This would follow Git conventions and would be very useful for FTP deployments. Thanks to that feature there would be ability to build assets before every push super easy.

**Comment by mkllnk** [comment]
I'm thinking of a `pre-ftp-push` hook.

The most common use cases for a pre-push hook are running tests on the code or checking for protected branches.

*running tests*
If you use a remote repository to push, you executed the tests for this commit already. You don't want to do it twice, right?

*check for protected branches*
Well, that doesn't work for ftp pushes. So we don't want to tun this on git-ftp push.

Another request in #244 was to check if you have pushed to the repository before you push to the ftp server. That is a check you don't want to do in the normal pre-push hook.

If you really want to run the pre-push hook, you can call it within the pre-ftp-push hook.

**Comment by mkllnk** [comment]
And if we are doing `pre-ftp-push`, we can do `post-ftp-push` as well, requested in #244.

**Comment by adriandmitroca** [comment]
Yes, that's pretty awesome approach to this problem.

**Comment by mkllnk** [comment]
I pushed a new change to the develop branch. It should call the hooks `pre-ftp-push` and `post-ftp-push`. There is an example in the man page. Please try it out and give feedback. :-)

**Comment by efes0** [comment]
Using the example in the man page (develop branch as of this commit: 80e9c04) if i have a "TODO" match then the `exit 1` will cause curl to exit out of the upload even if there are other files ready to be uploaded and i will have to either remove or ignore the "TODO" file to upload anything else.

On the other hand if you were to add `"$TMP_GITFTP_UPLOAD" "$TMP_GITFTP_DELETE"` to the `pre_push_hook` function then you can edit those files on the fly removing anything that you don't want uploaded or deleted.

Doing this: (notice items 5,6 in print_status)
```
pre_push_hook() {
	hook='.git/hooks/pre-ftp-push'
	if [ "$EXECUTE_HOOKS" -eq 1 -a -e "$hook" ]; then
		scope="${SCOPE:-$REMOTE_HOST}"
		write_log "Trigger pre-ftp-push hook with: $scope, $REMOTE_URL, $LOCAL_SHA1, $DEPLOYED_SHA1"
		print_status | $hook "$scope" "$REMOTE_URL" "$LOCAL_SHA1" "$DEPLOYED_SHA1" "$TMP_GITFTP_UPLOAD" "$TMP_GITFTP_DELETE" || exit "$ERROR_HOOK"
	fi
}
```

I was then able to do this: (notice the addition of `tmp_upload`, `tmp_delete` and `nul`)
allowing me to remove the path and nul char from the delete file so i don't delete those files on my ftp host
```
remote="$1"
url="$2"
local_sha="$3"
remote_sha="$4"
tmp_upload="$5"
tmp_delete="$6"

nul="\x00"

while read -r -d '' status file
do
    if [ "$status" = "D" ]
    then
        if [[ $file == *".css" ]] || [[ $file == *".js" ]] 
		then
			echo "css/js found in filename $file, not deleting remote file."
			echo $status $file
			sed -i "s|${file}${nul}||" $tmp_delete
        fi
    fi
done

exit 0
```

And while i didn't test the tmp_upload the tmp_delete did work for me

PS. 
1) the remote_url that you are printing out in write_log prints a blank space (no url/path)
2) this particular `sed` command apparently requires GNU sed

**Comment by mkllnk** [comment]
Thank you for your feedback. I was tempted to give these filenames to the hook script. But I thought that it would expose too much of the internals. Instead, I was thinking of the hook script producing new file lists. It could look like this:

```bash
remote="$1"
url="$2"
local_sha="$3"
remote_sha="$4"

while read -r -d '' status file
do
    if [ "$status" = "D" ] && [[ $file == *".css" ]] || [[ $file == *".js" ]] 
    then
        echo "css/js found in filename $file, not deleting remote file." 1>&2
    else
        printf '%s %s\0' "$status" "$file"
    fi
done

exit 0
```

The git-ftp script would need to read the output and work with that. Long term, we could also make the ignore and include mechanisms work the same way.

What do you think?

**Comment by efes0** [comment]
If i understand correctly you are talking about moving the editing that i am doing with `sed` to the git-ftp script and while that would make it easier for the end user it could leave you with some issues.

1) Are you going to do any potential rewriting in bash or are you going to introduce a 3rd party dependency with version dependent options (for example 'sed') which might have different "results" depending on the version you have installed. (i am not a developer nor do i know bash, so i don't know what you can or can't do)

2) Let's say that issue 1 is not an issue, how will the script know what to do with the output of the hook? will the user (hook) have to pass different flags to the git-ftp script telling it what to do? and if yes how many flags/options will you need to implement?

-
When you say 
> I was thinking of the hook script producing new file lists

What do you mean by that? considering that is exactly what i am doing with my sed command.

&nbsp;

As for the ignore and include mechanisms, considering that the man page says

> The standard input is a list of all filenames to sync. Each file is preceeded by A or D followed by a space. A means that this file is scheduled for upload, D means it's scheduled for deletion. All entries are separated by the NUL byte. This list is different to git diff, because it has been changed by the rules of the `.git-ftp-include` file and the `.git-ftp-ignore` file.

and therefor by the time the hook gets called the include/ignore files have already done their work, so what would you change?

&nbsp;
On a side note, I found that i had to add a `\n` to the end of this string `printf '%s %s\0'` for readability purposes otherwise it printed as one long string.

**Comment by mkllnk** [comment]
Okay, I have not been very clear. The hook script is fed with the list of files to upload or delete. The hook script is reading this list. Instead of changing files, it could output a different list with `printf '%s %s\0'`. That output is not meant for a human reader, but could be read by the git-ftp program. And this new list could be used to upload or delete. In that case, you don't need to touch the temporary files. This is not implemented, just an idea.

Completely independent from the hook script, before hooks are called, the ignore and include mechanisms could work the same way. They could just be like hook scripts. They read the file list from stdin and output a new file list on stdout. If we would change the git-ftp program that way, we would not need the temporary files any more.

**Comment by efes0** [comment]
so in short, the git-ftp script will look for output from the hook otherwise it will process it the way it does it till now using the temp files

if the git-ftp script will read the output of `printf '%s %s\0'` to control the upload/deletion of files instead of modifying the temp files then the git-ftp script will need some type of flag to know that it should process this particular output, because the script has no way of knowing what the end user has in their hook and they may have multiple outputs

the easiest way to flag it would probably be a flag/cmd at the beginning of every "line" of output similar to $status, otherwise perhaps a beg/end comment above and below this block of output

&nbsp;
considering just how well the temp files are baked into the script (there are 13 instances of '$TMP_GITFTP_UPLOAD' in the script), what would be the benefit of changing the ignore/include files to work like hook scripts, _and more importantly_ if you want to remove the temp files will it be worth the effort to rework the git-ftp script (I'm guessing that in the long run its easier to manipulate/work with temp files then working with stdin/stdout)

**Comment by mkllnk** [comment]
Thank you for all your thoughts. I think the quintessence is that it seems easier to work with the current temp files. Would you like to open a pull request with giving the name of the temp files to the hook script?
