### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by flesser** [git-ftp/git-ftp#238]
If I try to run the tests, the output looks like this:
```
grep: git-ftp-test.sh: File or directory not found
It took 0 seconds
Ran 0 tests.
OK
```

The problem seems to be that it performs the [oneTimeSetup](https://github.com/git-ftp/git-ftp/blob/develop/tests/shunit2-2.1.6/src/shunit2#L1022) where it [leaves the testing dir](https://github.com/git-ftp/git-ftp/blob/develop/tests/git-ftp-test.sh#L27) before it can [build the list](https://github.com/git-ftp/git-ftp/blob/develop/tests/shunit2-2.1.6/src/shunit2#L1030) of test functions [from the test script](https://github.com/git-ftp/git-ftp/blob/develop/tests/shunit2-2.1.6/src/shunit2#L971) it expects to be in the same directory. Since `pwd` is now `git-ftp/` instead of `git-ftp/tests/`, the file `git-ftp-test.sh` is not found anymore.

**Comment by mkllnk** [comment]
Thank you for bringing this up. We should avoid changing directories. But your pull request assumes that you call the script from the test directory. Ideally, it doesn't matter from which directory you call the tests. That's why the tests on Travis fail with your change.

The challenge is to get an absolute path to the git-ftp command reliably on different systems. I used `cd` and `pwd`. And that works perfectly in my shell and on the test systems. On which system are you testing? Which shell?
We could add another `cd -` to go back. Does that work for you?

But ideally we find a command that is available under Linux, OSX and Windows (msysgit, cygwin).

**Comment by flesser** [comment]
I just changed the PR to use an absolute `$TESTDIR` instead. It works for me (Linux, Bash) both for calling the script from within the test directory as well as from outside. Travis also seems to like it better. I haven't tested it on Windows.
