### ISSUE TITLE
test run without uploading anything

### ISSUE THREAD

**Issue by etech0** [git-ftp/git-ftp#241]
is there a way to have it run without actually uploading - but just have it generate a log file of which files will be uploaded, to where, and if any files will be overwritten?

Thanks!

**Comment by tuffz** [comment]
https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#options

> `-D`, `--dry-run`: Does not upload or delete anything, but tries to get the .git-ftp.log file from remote host.

in combination with

> `-v`, `--verbose`: Be verbose.

creates no log file, but generate an useful output in command line interface

**Comment by etech0** [comment]
Awesome - thanks!

Is there a way for it to show me the source and destination path of files that will be overwritten? I want to make sure that things are uploading to the right place, since this is a live site and I don't want to mess things up.

**Comment by mkllnk** [comment]
Well, if you do it with `-D -v`, then you will see a line like this:

```
Friday 26 February  09:17:22 AEDT 2016: Check if ftp://localhost/test/ is clean.
```

That is the path were everything gets uploaded to. After that is the list of all files that would be uploaded. But it doesn't check which files would be overwritten since it is completely normal to overwrite files.

You could do a test run into a sub-directory and check that everything works as expected. If you use `-vv`, you will see verbose output of curl which gives you every single ftp command executed.

**Comment by etech0** [comment]
Thanks!

I ran a dry run with verbose, and it didn't mention any files to be uploaded. I know there was one file I committed, and comparing it to the file on the server I see that the server needs to be updated.

**Comment by mkllnk** [comment]
Did you change it before you ran `git ftp checkup`? The checkup tells git-ftp that everything is up-to-date. If you know which commit is on the server, you can use `-c <commit-id>` option to upload all changes since the given commit. Look into your git history to find the commit before that change you did.

**Comment by etech0** [comment]
I did - I guess that explains it.

Thanks!
