### ISSUE TITLE
Push outside the folder

### ISSUE THREAD

**Issue by sweebee** [git-ftp/git-ftp#260]
I want to pull a repository to a ftp server with php, but is there a way to set a directory? For pulling I use this:

```
shell_exec("sudo git --git-dir=/folder/rep/.git pull 2>&1 &");
```

--git-dir wont work with ftp. Also tried this but won't work (gives dirty repository):

```
shell_exec("cd /folder/rep/ && git ftp push 2>&1 &");
```

**Comment by mkllnk** [comment]
Git-ftp can push your local files to an FTP server. But your example looks like your files are on the server already. In that case you could clone the repository once and then pull to update

```sh
# You need an empty directory for this:
git clone /folder/rep ./

# deploy from /folder/rep is then as easy as:
git pull
```

The error message 'dirty repository' is caused by changed files. You need to commit everything or stash it before you can use git-ftp.

**Comment by mkllnk** [comment]
The `--git-dir` option is currently not supported by Git-ftp. But you should be able to use the environment variable `GIT_DIR`. Same with `--work-tree` and `GIT_WORK_TREE`.

It would be a good idea to add support for these parameters. Git sets the variables `GIT_DIR` and `GIT_WORK_TREE` before invoking git-ftp. In git-ftp we would just need to export these into the environment to pass them on to all git calls.

**Comment by iamhabbeboy** [comment]
please i need help on how to push directory with files outside git init folder

**Comment by vgrados2** [comment]
I just did it in windows
