### ISSUE TITLE
How can I verify that it's a secure FTP connection?

### ISSUE THREAD

**Issue by Gantron1** [git-ftp/git-ftp#277]
I have set my ftp host to an ftpes:// address but have done nothing else to ensure a secure connection. How can I be sure the ftp connection is really using encryption, mainly for the login info?

**Comment by mkllnk** [comment]
If you add the `-vv` flag you will see all debug output of the underlying curl commands. You will see what it does. You can try that with a false password first. It will fail, but you will see how it attempts to connect.

**Comment by tele1** [comment]
For future.
Maybe github have encryption.
But ftp don't use encryption.
Only sftp use encryption, when it is used via ssh.
To check internet connection, are tools for listening, for example nc for Linux.
https://linux.die.net/man/1/nc
For example if you will see unencrypted password in terminal with **nc**, during login, 
then the connection may not be encrypted.

**Comment by LukasFritzeDev** [comment]
> Maybe github have encryption.

Since GitHub is mostly requested over HTTPS protocol, transport encryption is used, yes

> But FTP don't use encryption.
Only SFTP use encryption, when it is used via ssh.

And yes, SSH connections are encrypted as well. And since SFTP is _SSH File Transfer Protocol_ or _“FTP over SSH”_ connections with SFTP are encrypted as well.
But not only those. Same as for HTTP there are FTP protocols using SSL/TLS encryption: FTPS and FTPES. Okay FTPES is only the **e**xplicit variant but they are encrypted as well.

But your tip using nc to check the transported data is interesting. Thanks for this addition. In most cases adding `-vv` to see the debug info of git-ftp would be enough, I think :)

**Comment by tele1** [comment]
Last time I tried use nc. Basic options are for something other.
Perhaps this is possible, but I think it is complicated.
`tcpdump -X  > log.txt`
looks more easy to use.
