### ISSUE TITLE
Submodule handling?

### ISSUE THREAD

**Issue by Gantron1** [git-ftp/git-ftp#295]
I have a project with git submodules. I ran "git ftp init" on the parent repo, and this worked just fine. However there were zero byte files named the same as the submodule directories. This prevented me from doing "git ftp init" on the submodules.

As an experiment, I replaced the zero byte file with the directory, and then "git ftp init" worked just fine on the submodule. However, after this, "git ftp push" quit with an error, probably because it could no longer upload the zero byte file anymore.

How can I get git-ftp to work if the repo has submodules?

**Comment by mkllnk** [comment]
Unfortunately, the support for submodules doesn't work in all circumstances and needs to be re-written. You could try an older version of Git-ftp, but it will lack some features.

Which operating system do you use?

**Comment by Gantron1** [comment]
Ubuntu 16.04. What features will be missing?

**Comment by mkllnk** [comment]
You find the features that were added in the [changelog file](https://github.com/git-ftp/git-ftp/blob/master/CHANGELOG.md). The push should work from the root repository. There should not be any need to go into the submodules and push them individually.

But that makes me think of another workaround. You could list the submodules in `.git-ftp-ignore` and then go into the submodules to push from there. That could work with this line:

```sh
git submodule foreach git push
```

**Comment by Gantron1** [comment]
I like this second idea. However, do you mean `git submodule foreach git ftp push`? (i.e. with `ftp` between `git` and `push`?)

**Comment by mkllnk** [comment]
Oh yes, sorry, I meant: `git submodule foreach git ftp push`

Let us know if that works. The downside is that you need to init every single module first and set the config.

**Comment by Gantron1** [comment]
Yes, it worked perfectly, and I'm already init'ing and setting the config for each submodule anyway. Thanks!

**Comment by tuffz** [comment]
👍

**Comment by DerTanzschuh** [comment]
I think I might have found a fix for this issue. I had the same problem. The debugging showed me that git-ftp was uploading an empty file for the submodule during init, instead of creating a directory.

The function `handle_file_sync()` ([Line 768](https://github.com/git-ftp/git-ftp/blob/ffd3e10c37f22761a06a92641ee9561b97eb98e0/git-ftp#L768)) checks if a file is a submodule or a regular file. It turns out this check is never true, even for submodules.

The check itself is quite simple ([Line 245](https://github.com/git-ftp/git-ftp/blob/ffd3e10c37f22761a06a92641ee9561b97eb98e0/git-ftp#L245)), but it depends on the content of `GIT_SUBMODULES`. This variable is set in `cache_git_submodules()` in [Line 242](https://github.com/git-ftp/git-ftp/blob/ffd3e10c37f22761a06a92641ee9561b97eb98e0/git-ftp#L242). To get the list of submodules the variable `SYNCROOT` is used. 

**And here lies the problem.×
**The moment the function `cache_git_submodules()` is called the `SYNCHROOT` is not set yet, it still has its default value `""`.** 

The call stack looks like this (simplified):
```
main
  - cache_git_submodules
  - handle_action
    - action_*
        - set_remotes
          - set_syncroot
```
and this is where is the variable `SYNCROOT` finally set up.

If I set the default value for `SYNCROOT` to `"."` the variable `GIT_SUBMODULES` is set correctly and therefore everything is working fine.

Is there a reason for setting `SYNCROOT` that late? Also, in my opinion, it’s quite confusing to set it up in a function called `set_remotes()`, because to me this sounds like a function for the server (remote) settings, but syncroot is a property for the local environment, isn’t it? 
And another thought I had: Why is `SYNCROOT` used at all at this point? Wouldn’t it be enough to use the base directory of the git repo or just "." in this case? Do the submodules really depend on the syncroot? Is this a tweek to make recursive submodules (submodules of submodules) work?

Following the thoughts above, I think there could be two possible fixes:

1. call `set_syncroot` at the beginning of `cache_git_submodules` (just before  [Line 242](https://github.com/git-ftp/git-ftp/blob/ffd3e10c37f22761a06a92641ee9561b97eb98e0/git-ftp#L242) or at another point before this) to make sure it is set correctly in the moment of it’s first use.
2. remove the part `-- "$SYNCROOT"` from [Line 242](https://github.com/git-ftp/git-ftp/blob/ffd3e10c37f22761a06a92641ee9561b97eb98e0/git-ftp#L242) to make git show every submodule independently from current directory or syncroot.

Both approaches work in my simple test project (one simple submodule).
What do you guys think is the better way to go? Did I miss something?

There still is a problem with SFTP, but i think this is the scope of another issue.

**Comment by DerTanzschuh** [comment]
> Wouldn’t it be enough to use the base directory of the git repo or just "." in this case? Do the submodules really depend on the syncroot? Is this a tweek to make recursive submodules (submodules of submodules) work?

I have now created a project with a nested submodule. It has the following structure.

```
main-repo
    - submodule
        - nested-submodule
```

Both proposed solutions seem to work fine. All files, even the ones of the nested submodule are uploaded correctly during init action (with protocol `ftpes`).

**Comment by mkllnk** [comment]
Hallo @DerTanzschuh. Thank you for the detailed analysis. It explains a lot. The solution is to set `SYNCROOT` early.

If you were to omit `SYNCROOT` then `GIT_SUBMODULES` can contain submodules outside of the syncroot. And that would mean that `git ftp catchup` would run in submodules outside of the syncroot which we don't want.

Would you be happy to submit a pull request for this?
