### ISSUE TITLE
mktemp Error On Alpine Linux

### ISSUE THREAD

**Issue by amayer5125** [git-ftp/git-ftp#323]
I get error `mktemp: Invalid argument` on Alpine Linux. Alpine uses the busybox version of mktemp.

The docs state
> TEMPLATE must end with XXXXXX (e.g. [/dir/]nameXXXXXX).

I believe we just need more X's on the end of [Line 953](https://github.com/git-ftp/git-ftp/blob/af120665e9775e1b0a525b3005604318d60c11f1/git-ftp#L953)

**Comment by mkllnk** [comment]
Would you be tempted to provide a Travis configuration that tests Git-ftp with busybox?

**Comment by amayer5125** [comment]
I can look into it later this week. I'm out of town today.

**Comment by amayer5125** [comment]
@mkllnk I was looking over your tests. Im not sure how to go about making a test for busybox. It looks like you just run a bunch of bash functions to do your tests. The only requirement your script really has with busybox is that mktemp template must end in "XXXXXX".
I have not worked with Travis CI before (I am more familiar with GitLab). Is there a direction you could point me in for what you are expecting?

**Comment by mkllnk** [comment]
In Travis you can run the same tests in different environments. At the moment, they run on Ubuntu Linux and on OSX. On both they run once with lftp installed and once without. So I thought we could run it with a busybox environment as well. But I have never worked with busybox. If you could setup one script that installs busybox on Ubuntu and sets up the environment so that the tests are using busybox, then I can integrate that into the Travis tests.

If you activate Travis for your fork, it will run the tests whenever you push.
