### ISSUE TITLE
Incorrect Exitcode on unknown SHA1 Object

### ISSUE THREAD

**Issue by tuffz** [git-ftp/git-ftp#334]
Hi,

I am currently deploying my Project via a Gitlab-CI Server. Everything works fine. But sometimes if I deploy a different branch than the usual one git-ftp doesn't recognize the SHA1 Object. I am not too sure why that happens. 

But that is not the real issue I have at the moment. For a starter it would be great if my Gitlab-CI would not succeed. Meaning git-ftp should throw an exitcode 1. That way the Gitlab-CI will recognize the failure and display a not succeded build. 

This is the output I receive from my Gitlab-CI Server:

```
$ git ftp push -u $DEV_FTP_USER -p $DEV_FTP_PASSWORD $DEV_FTP_URL
Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
Do you want to ignore and upload all files again? [y/N]: Aborting...
Build succeeded
```

Thanks

**Comment by mkllnk** [comment]
Ah, I see. That's the downside of expecting user input. I thinks you "chose" to abort and therefore there is no error. I would be happy about a pull request that gets rid of that question. Instead it could suggest to run the same command with the `--force` again. That's how Git error messages are usually helpful. It would be a behaviour change though and needs to bump up the version number.

As a dirty quick fix, you could check the output and fail if this text comes up.

And about the root cause: Maybe your deployment tool tries to be efficient by cloning with the `--single-branch` option. It then knows only about commits in the history of that branch.

**Comment by l0rdseth** [comment]
+1

**Comment by amayer5125** [comment]
Maybe a solution would be to make a `-i` or `--interactive` option that asks the question? and if the option is not specified it will return an exit code.

**Comment by tuffz** [comment]
bump up after merging of #331

**Comment by mkllnk** [comment]
What do you think about https://github.com/git-ftp/git-ftp/pull/353?
