### ISSUE TITLE
Ignore folder with .git-ftp-ignore

### ISSUE THREAD

**Issue by jmbelloteau** [git-ftp/git-ftp#350]
Hello,

I would like to know how to ignore a complete folder from being upload?

Here is what my **.git-ftp-ignore** file looks like.
But the folders **src** and **tools** are stills being uploaded

```
src
tools
.babelrc
.editorconfig
.eslintignore
.eslintrc
.git-ftp-ignore
.gitignore
.gitlab-ci.yml
.stylelintignore
.stylelintrc
CHANGELOG.md
composer.lock
gulpfile.js
package.json
README.md
yarn.lock
*/.gitignore
```

**Comment by luxlogica** [comment]
@jmbelloteau Did you try `src*` or `src/*`?

**Comment by jmbelloteau** [comment]
@luxlogica nope let me try 😄

**Comment by luxlogica** [comment]
You may also want to try `.git*` to ignore all files that begin with ".git" - and `.eslint*`and `.stylelint*`.

**Comment by jmbelloteau** [comment]
@luxlogica my results:

for folder -> `foldername*` seems to work
for files -> `namepatern*` seems to work

thanks 😄

**Comment by jimblue** [comment]
Hi @luxlogica  !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by dkjain** [comment]
gud to know
