### ISSUE TITLE
--insecure works but how to fix it? curl: (51) SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by tarach** [git-ftp/git-ftp#396]
I'm getting error message:
curl: (51) SSL peer certificate or SSH remote key was not OK
Adding --insecure works but I don't want "not to verify the host"

I'm running Cygwin on Windows7 on my other machine at work with the same setup git ftp commands works ok. ( different server though )

Is it server or client issue and how can I fix it?
~Thanks

**Comment by mkllnk** [comment]
You need the server's fingerprint in your `known_hosts` file. The easiest way to do that is to connect via `ssh` and say "yes" to adding the fingerprint. Have you tried that? If yes, then your curl version and your ssh version use different types of fingerprints. I don't have a solution for that yet, but it should be possible to add the right one.

**Comment by tarach** [comment]
I already did it. I'm connecting with my server via SSH and SFTP without giving password. But for some reason git-ftp ( or apparently curl here ) needs something else.

Any ideas?

**Comment by a-hulman** [comment]
Same here, when I open ~/.ssh/known_hosts in bash, I see the host is already present, but git ftp push reports:
$ git ftp push --verbose
Fri, Mar 16, 2018  7:35:36 PM: git-ftp version 1.4.1-UNRELEASED running on MINGW64_NT-10.0 DESKTOP-NC5562I 2.8.0(0.310/5/3) 2017-04-02 13:38 x86_64 Msys
Fri, Mar 16, 2018  7:35:38 PM: Host is 'ftp.***.com:22'.
Fri, Mar 16, 2018  7:35:38 PM: User is '***'.
Fri, Mar 16, 2018  7:35:39 PM: Password is set.
Fri, Mar 16, 2018  7:35:39 PM: CACert is ''.
Fri, Mar 16, 2018  7:35:39 PM: Insecure is '0'.
Fri, Mar 16, 2018  7:35:40 PM: Path is ''.
Fri, Mar 16, 2018  7:35:40 PM: Syncroot is ''.
Fri, Mar 16, 2018  7:35:40 PM: The remote sha1 is saved in file '.git-ftp.log'.
Fri, Mar 16, 2018  7:35:40 PM: Retrieving last commit from sftp://***:***@ftp.****.com:22/.

curl: (51) SSL peer certificate or SSH remote key was not OK
Fri, Mar 16, 2018  7:35:41 PM: fatal: Could not get last commit. Network down? Wrong URL? Use 'git ftp init' for the initial push., exiting...

**Comment by mkllnk** [comment]
In that case `ssh` and `curl` use different fingerprints. I just found a nice [answer on serverfault.com](https://serverfault.com/a/802556/409760) saying that his could help:
```sh
ssh-keyscan hostname.example.com >> ~/.ssh/known_hosts
```

Let us know if that works.

**Comment by a-hulman** [comment]
Hello again,
after some tinkering, it seems my git installation is somehow flawed. All git tools like ssh and curl are NOT working with /users/user/.ssh

While using bash, ssh or other related tools outside git(from shell) use proper folder!

I overwrote git's binaries in mingw64/bin with binaries and dlls from cygwin bin folder and voila! the known hosts works as expected, although there are some warnings on non existing /tmp folder. I guess I'll rather reinstall cygwin and git.

Reading this after me, it's a mess, sorry, but I hope you can get the idea :)

**Comment by tarach** [comment]
I think I've figured it out and I don't have this issue anymore. ( or not I don't really remember ) 

It's an issue ( in my case ) with the list of certificate authorities. Update those and it might help you.

**Comment by JoshuaCrewe** [comment]
I would like to throw in my two cents here. I was having this problem and came across this issue.

The problem I was having was what @mkllnk  described. Specifically that ssh was saving connections as `ecdsa-sha2-nistp256` ( before it was using `ssh-rsa` ) in `~/.ssh/known_hosts` . 

This issue can be followed [here](https://github.com/libssh2/libssh2/issues/129).

Curl was not able to read `ecdsa-sha2-nistp256` so couldn't establish a secure connection.

To fix this incompatibility I was able to set ssh ( libssh2 ) to resume using ssh-rsa in the known_hosts file. The [ssh config options](https://www.ssh.com/ssh/config/) have an option to set `HostKeyAlgorithms`. 

I amended my `~/.ssh/config` with `HostKeyAlgorithms=ssh-rsa`, removed the server entry from `~/.ssh/known_hosts` ( I renamed the file to start again ), ssh'd into the server to save a new entry and every thing was as it was before.

I hope this helps anyone else who stumbles on this thread. I assume that this happened because libssh2 / curl was updated which means there isn't much this project can do ?

**Comment by camlafit** [comment]
Hello

As linked by @JoshuaCrewe , libssh2 can now support ecdsa-sha2-nistp256 in 1.8.0 released in may 2018.
The problem some stable distribution as debian provide only 1.7.0 without any backports. 
We can hope to solve it without any workaround with next major distribution update (at least on Linux ecosystem)

Actually @JoshuaCrewe workaround is better way to get git and git-ftp updated , thanks a lot :)

**Comment by prattak86** [comment]
I know this is closed, but the very initial response by @mkllnk worked perfectly for me. Thanks for this!
