### ISSUE TITLE
Curl Permission Denied 

### ISSUE THREAD

**Issue by anoopd** [git-ftp/git-ftp#409]
Here is the `git ftp catchup -v`  result  for my sftp . When i connect with CyberDuck  the path is `/home/username/html `  

    Sun Jan  7 17:44:44 IST 2018: git-ftp version 1.4.0 running on Darwin Anoops-MacBook-Air.local 15.6.0 
    Darwin Kernel Version 15.6.0: Mon Nov 13 21:58:35 PST 2017; root:xnu-3248.72.11~1/RELEASE_X86_64 
    x86_64
    Sun Jan  7 17:44:45 IST 2018: Host is 'hostname'.
    Sun Jan  7 17:44:45 IST 2018: User is 'username'.
    Sun Jan  7 17:44:45 IST 2018: Password is set.
    Sun Jan  7 17:44:45 IST 2018: Using ssh private key file /Users/anoopd/.ssh/id_rsa
    Sun Jan  7 17:44:45 IST 2018: Automatically using ssh public key file /Users/anoopd/.ssh/id_rsa.pub
    Sun Jan  7 17:44:45 IST 2018: Path is ''.
    Sun Jan  7 17:44:45 IST 2018: Syncroot is '/'.
    Sun Jan  7 17:44:45 IST 2018: The remote sha1 is saved in file '.git-ftp.log'.
    Sun Jan  7 17:44:45 IST 2018: CACert is ''.
    Sun Jan  7 17:44:45 IST 2018: Insecure is '1'.
    Sun Jan  7 17:44:45 IST 2018: Uploading commit log to sftp://username:***@hostname/.git-ftp.log.

    curl: (9) Upload failed: Permission denied (3/-31)
    Sun Jan  7 17:44:48 IST 2018: fatal: Could not upload file: '.git-ftp.log'., exiting...
    Sun Jan  7 17:44:48 IST 2018: fatal: Could not upload., exiting...

Is the problem due to incorrect Syncroot setting ? Please help .

**Comment by DerTanzschuh** [comment]
Sorry for that late answer. Maybe you have been able to solve the problem yourself by now.

The error message indicates, you don’t have write access to the directory. In most cases this caused by a incorrect `remote-root`. (The syncroot is the local directory, the remote-root is the destination.)

If you have the path `/home/username/html` in your FTP-Client you could set this as your syncroot. There are different ways to do this. But be careful not to forget the `/`in the beginning to set the absolute path. Or use a path relative to your home directory. This can be done using a `~`. 

The following version should be all the same, but in some cases only the absolute paths are working.
```
url = sftp://hostname.tld/
remote-root = /home/username/html
```
```
url = sftp://hostname.tld//home/username/html
```
Note the double `//` in this example.

```
url = sftp://hostname.tld/
remote-root = ~/html
```
```
url = sftp://hostname.tld/~/html
```
Yes, with SFTP the `~` has to be in the URL. There is another example for this with more explanations in the [manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#first-uploads).
