### ISSUE TITLE
.git-ftp-ignore works just both on local and remote?

### ISSUE THREAD

**Issue by didiraja** [git-ftp/git-ftp#420]
### Question ?

I'm trying to use Git FTP on my old projects, so that means, projects already installed with other folder and directories that doesn't have any relation with the local project.

Does the .git-ftp-ignore only works to ignore my local files ou it works to ignore **remote files that are not tracked** by Git?

### Environment

**LOCAL:**

```
.git
.git-ftp-ignore
src/
dist/
gulpfile.js
```

**REMOTE:**

```
dist/
.htaccess
blog/
file.pdf
file.php
```

I want to ignore `.htaccess`, `blog/`, `file.pdf` and `file.php` that only existe in remote and are not tracked by Git.

**Comment by DerTanzschuh** [comment]
Maybe the answer comes a litte too late and you found a solution in the meanwhile. Nevertheless I’ll answer it. It might help others.

I hope I understood your question correctly. You have your project already on the server and wan’t to use git-ftp from now on to sync your upcoming changes. But you don’t want to get the other files deleted. Am I right with this?

(In your setup there is no `.gitignore` so I'll assume you don’t ignore your `dist/` directory in git.)

**git-ftp touches only files you have tracked by git and that are changed since the last push** (or files defined in `.git-ftp-include`). So the files you listed will stay untouched on the server even if you don’t have them listed in your `.git-ftp-ignore` file.

So git-ftp would upload your changed files in `dist/`, `src/` and even `gulpfile.js`, but not delete the other ones on the server.

---

I'm assuming that you don’t wan’t to have all these stuff on the server but only the `dist/` directory. And that’s exactly where `.git-ftp-ignore` is meant to be used for. So to upload only the `dist/` dir you can list the files and directories in `.git-ftp-ignore` to exclude them from uploads. So your `.git-ftp-ignore` file could look like this
```
.git-ftp-ignore
src/
gulpfile.js
```
(Yes we don’t want to have `.git-ftp-ignore` on the server either. It’s only a file for local processing.)

Theoretically you can list the other files as well, there will be no harm with this. But If you decide to add them later, you might have forgotten about this and will wonder why they are not uploaded.

**Comment by didiraja** [comment]
Better late than never! I solved that long ago, but It's cool see it written clearly.
