### ISSUE TITLE
Only folders defined in .git-ftp-include are uploaded

### ISSUE THREAD

**Issue by paulcanning** [git-ftp/git-ftp#430]
I'm running git-ftp in pipelines, and have some folders (created by composer) that need uploading as well.

I added them to .git-ftp-include as:

```
!wp/
!vendor/
```

But now only those two folders are uploaded. Any files in the root of the repo are not uploaded.

I thought git-ftp would upload all files, plus ones added to the include file?

**Comment by mkllnk** [comment]
All changed files plus those in .git-ftp-include is the expected behaviour. Can you give any more information on this?

**Comment by paulcanning** [comment]
That's what I thought, but it wasn't the case. There is no more info other than it doesn't work. I've had to add the files and folders that are in the repo to the .git-ftp-include file as well.

**Comment by akarupt** [comment]
Every time i run git-ftp all files in .git-ftp-include are sent. Is it possible to create a hash file at root like the SH1 you create Ex: for every entry in .git-ftp-include you create a hash in the server when you sent. if the local hash of the directory/file is diferent or not existent you sent. Ex of remote file:
dir1=aslçkdjçlkhj12lk3
dir2=asdasd
file1=asdasdasd

Only when the comparing keys are diferent you sent the folder/file.

**Comment by mkllnk** [comment]
I'm sorry, but I can't reproduce the error. Can you tell me some details?

* Git-ftp version you are using
* provide a zip file with the repository you try to upload

**Comment by phamshantuyet** [comment]
Hi
I try use .git-ftp-include but it not works
_files_.txt:phpinfo.php
test.txt
!/var/jenkins_home/workspace/my/_files_.txt
/var/jenkins_home/workspace/my/_files_.txt
!_files_.txt
_files_.txt
_files_\.txt
!_files_\.txt

/var/jenkins_home/workspace/my/ is a git folder

/usr/bin/git-ftp -vv push --remote-root /data/www/my/ ftp://10.0.2.157/

Log:
Sun Jun  3 05:34:22 UTC 2018: git-ftp version 1.3.1 running on Linux b44588d6d205 4.4.0-116-generic #140-abc SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 GNU/Linux
Sun Jun  3 05:34:22 UTC 2018: Host is '10.0.2.157'.
Sun Jun  3 05:34:22 UTC 2018: User is 'abc'.
Sun Jun  3 05:34:22 UTC 2018: Password is set.
Sun Jun  3 05:34:22 UTC 2018: Path is '/data/www/my/'.
Sun Jun  3 05:34:22 UTC 2018: Syncroot is ''.
Sun Jun  3 05:34:22 UTC 2018: The remote sha1 is saved in file '.git-ftp.log'.
Sun Jun  3 05:34:22 UTC 2018: CACert is ''.
Sun Jun  3 05:34:22 UTC 2018: Insecure is ''.
Sun Jun  3 05:34:22 UTC 2018: Retrieving last commit from ftp://abc:***@10.0.2.157//data/www/my/.
*   Trying 10.0.2.157...
* TCP_NODELAY set
* Connected to 10.0.2.157 (10.0.2.157) port 21 (#0)
< 220 (vsFTPd 3.0.3)
> USER abc
< 331 Please specify the password.
> PASS xxxxxxxxxxxxxxxxxx
< 230 Login successful.
> PWD
< 257 "/home/abc" is the current directory
* Entry path is '/home/abc'
> CWD /
* ftp_perform ends with SECONDARY: 0
< 250 Directory successfully changed.
> CWD data
< 250 Directory successfully changed.
> CWD www
< 250 Directory successfully changed.
> CWD my
< 250 Directory successfully changed.
> EPSV
* Connect data stream passively
< 229 Entering Extended Passive Mode (|||40093|)
*   Trying 10.0.2.157...
* TCP_NODELAY set
* Connecting to 10.0.2.157 (10.0.2.157) port 40093
* Connected to 10.0.2.157 (10.0.2.157) port 21 (#0)
> TYPE I
< 200 Switching to Binary mode.
> SIZE .git-ftp.log
< 213 41
> RETR .git-ftp.log
< 150 Opening BINARY mode data connection for .git-ftp.log (41 bytes).
* Maxdownload = -1
* Getting file with size: 41
{ [41 bytes data]
######################################################################## 100.0%* Remembering we are in dir "/data/www/my/"
< 226 Transfer complete.
* Connection #0 to host 10.0.2.157 left intact

Sun Jun  3 05:34:23 UTC 2018: Last deployed SHA1 for 10.0.2.157//data/www/my/ is 708fdc7bc1162b6bff1f8fd7b7b87e50dec8508b.
Sun Jun  3 05:34:23 UTC 2018: No changed files for 10.0.2.157//data/www/my/. Everything up-to-date.

file _files_.txt is not in git, and it is not uploaded to remote

Thanks

**Comment by DerTanzschuh** [comment]
In my regular tests I can't reproduce the error either.

My `.git-ftp-include`is set up like this and everything I expected to upload is uploaded. Note that these are also ignored in `.gitignore`.
```
!files.txt
!ignored/
```

---

But there is a very special scenario where the behavior @phamshantuyet described can occur. The error message you got indicates you have already pushed to your server and the commit on the server is the same as your currently checked out commit.

Let’s say we have a repository with the following setup.

You said _“ file files.txt is not in git,”_ so `.gitignore` will look like this:
```
random.file
stuff/
files.txt
.git-ftp-include
```
Please note I have also added `.git-ftp-include` here, but It’s empty at this moment or at least `files.txt` is not listet in it, cause you added it recently:
```
!random.file
```

- You push your repository to the server with your current state. 
- Now you recognize you forgot to add `files.txt` to your `.git-ftp-include`. You add it there. But because `.git-ftp-ignore` is ignored for git you still have a clean repo.
- And you try to push again. git-ftp does its stuff and it does not complain about a dirty repository so it catches the hash from the server. Since this hash is the hash of the current commit git-ftp has no reason to do any stuff (no changed files) and exits with the message you noted above.

A few condition must be met to run into this:
1. You have already pushed to your server
2. You change only files that are ignored, so your repo is clean without doing a commit
3. You edit your ignored `.git-ftp-include` (if it’s not ignored 2 would not be true)

Maybe there are some other edge cases where this can happen. But it might be that @paulcanning did a similar thing in his pipeline. If the `.git-ftp-include` file is ignored but extended with the additions during the pipeline processing, all the conditions described above are met. Just a guess cause we don’t have that much and detailed information here.

@paulcanning @phamshantuyet Can you confirm this guess? Is that the cause of the problem?
