### ISSUE TITLE
Where is git-ftp.log file stored locally?

### ISSUE THREAD

**Issue by DNTech** [git-ftp/git-ftp#434]
After successfully uploading files, a  **.git-ftp.log** file is uploaded on to the **root folder** of the **server** .... I just want to know the **location** of that particular file in my **local git repository** ..I want to manually change the **.git-ftp.log** file of the **server** to match the one **stored locally**

**Comment by mkllnk** [comment]
It is not stored on your local machine. The `.git-ftp.log` file on the server is only there to save the state in which the server is in. Every time you call `git ftp push`, it first downloads that file from the server to know in which state it is in, because it could have been changed from another computer. You can do whatever you like on your computer and if you want to push your currently checked out commit, you do `git ftp push`. If you want to override the value of `.git-ftp.log` on the server, you can use `git ftp catchup`:
```sh
git checkout branch-believed-to-be-on-the-server
git ftp catchup
# .git-ftp.log contains the commit id of the branch "branch-believed-to-be-on-the-server"
git checkout new-stuff-to-deploy
git ftp push
# only changes between branch-believed-to-be-on-the-server and new-stuff-to-deploy are uploaded
```

If you are deploying something new anyway, a little shortcut is this:

```sh
git checkout new-stuff-to-deploy
commit_on_the_server="$(git rev-parse branch-believed-to-be-on-the-server)"
git ftp push --commit "$commit_on_the_server"
```

The end result is the same.
