### ISSUE TITLE
Allow curl to use ~/.netrc

### ISSUE THREAD

**Issue by andypillip** [git-ftp/git-ftp#453]
As documented in the man page, thanks to #66, `curl` can use the `~/.netrc` file to retrieve login name and password.

Apparently usage of that file changed to optional, so one needs to use a switch: `curl --netrc`.

This means the documented feature doesn't work anymore with git ftp.

#267 is talking about another argument for curl, as mentioned there already it would probably be most useful to allow for a generic curl command line string in configuration?

Thanks!

**Comment by DerTanzschuh** [comment]
As far as I can see, the support for `--netrc` was added in this commit: https://github.com/git-ftp/git-ftp/commit/cdfc948e3a854933426b861d00ce4a6baedd23b7

It has changed since then but it’s still there:
https://github.com/git-ftp/git-ftp/blob/d496de9b3dfb433db9774dc14e5debe6f6a58009/git-ftp#L387-L389

**Comment by mkllnk** [comment]
Great, so https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#netrc needs an update to describe this.
