### ISSUE TITLE
delete should be first, for windows is not case sensitive

### ISSUE THREAD

**Issue by wanghan519** [git-ftp/git-ftp#455]
### Enhancement
there is a 'aaa.txt' file on windows ftp server.
i delete 'aaa.txt' and create 'AAA.txt' in git.
i commit and push ftp.
if upload first, 'AAA.txt' will be deleted then.
so delete first maybe better.

**Comment by markparnell** [comment]
Ideally this should be configurable.

Your Windows use case is definitely an issue, but personally I'd much rather see delete happen last. I work primarily with PHP and if files are removed or renamed, when I push the site goes down temporarily because files are deleted before other files which reference them are updated. For me, the best order would be create new files, then update modified files and finally delete removed files as this would significantly reduce down time during deployments.

**Comment by wanghan519** [comment]
thank you.
