### ISSUE TITLE
How to push with Sourcetree

### ISSUE THREAD

**Issue by Miri92** [git-ftp/git-ftp#461]
### Question

Pusing with command line it is working. But i want to push with Sourcetree. Because with command line it takes 2 step: 1, commit  2, push. In Sourcetree we can commit and push with one click.

**Comment by Jim-JZ-Chen** [comment]
I have the same question, is it possible to make a plug-in to Sourcetree or FileZilla?

**Comment by PeterEmil** [comment]
You tried `git commit -m "comment" && git ftp push`?

**Comment by DerTanzschuh** [comment]
As far as I know there is no plugin support in sSourcetree. But maybe you can use one of the [Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks).

You could set an action for the hook `post-commit` or `pre-push` to `git-ftp push` your changes. Since Sourcetree just calls basic git commands behind the scenes, this should work. But be aware that this will run on every commit or push. I’d probably go for the `pre-push` hook. It runs only if you push to a remote repository and not after every single commit. So you can push manually with Sourcetree or use the option in Sourcetree to automatically push your commit after creating it.

A more detailed description on Git Hooks and some useful links can be found here: https://githooks.com

**Comment by DerTanzschuh** [comment]
Oh. An there is even a example implementation how this could work here: #478 
You could try this.
