### ISSUE TITLE
SFTP  Could not open directory for reading

### ISSUE THREAD

**Issue by tihefrequi** [git-ftp/git-ftp#496]
### Bug  / Question ?

try to create a new directory with sftp  always ends in following erro:

```curl: (78) Could not open directory for reading: No such file or directory```

* How to reproduce the issue?
my config:
```
+ cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[git-ftp]
        password = ************
        user = myuser
        url = sftp://myserver.1and1-data.host:22
        syncroot = target
        remote-root = nightly/buildnr

```
my call:
``` git-ftp push --auot-init -vv --disable-epsv --force```
result: ```curl: (78) Could not open directory for reading: No such file or directory```

* Directory structure
`nightly` is existing directory
`buildnr` should be created by git-ftp

i doesnt know much about shell but i tried to make me a simple hack see: 
#497 

But if i ues `ftp` it works like a charm

### Environment
/usr/bin/bash

Linux e2a0e15757c6 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
git-ftp version 1.5.1

**Comment by tihefrequi** [comment]
maybe it is related to this  bug:
[Bug 2150 - Recursive upload expects target directory to already exist](https://bugzilla.mindrot.org/show_bug.cgi?id=2150)

**Comment by DerTanzschuh** [comment]
I did some research and testing on this topic. The curl command called looks something like this:

```sh
curl --key /path/to/key.key --pubkey /path/to/pubkey.pub --ftp-create-dirs sftp://user:@host//home/user/sftp-test/create-this-dir/
```

If called with `FTPS` or `FTPES` instead of `SFTP` it works as expected, which means it is creating the directory. Using `SFTP` does not work – the directory is not created.
The fun part is: if you try to upload a file to this non existing directory (with `-T` or `--upload-file` like you are doing it in your hack) the directory is created. I can’t find a way to force curl to create the directory on reading.

I’ll try another solution for this and create a pull request if i succeed.

**Comment by swinggraphics** [comment]
> But if i ues `ftp` it works like a charm

Same problem here, except I don't have anything fancy like syncroot or remote-root, and all my directories already exist on the server. It looks like the fix was incorporated over a year ago, so is my issue  related or something new? When I try init I get this error: "Could not open directory for reading: No such file or directory". The directory is actually created, however, and when I rerun init I get "mkdir command failed: Operation failed". Simply changing from SFTP to FTP makes the problem go away, but obviously I'd prefer not to be sending passwords in plain text. I have also verified the connection and mkdir by using sftp on the command line myself without issue.

**Comment by LukasFritzeDev** [comment]
Are you sure you are using the current version of git-ftp (1.6.0)? Whats the output of `git ftp --version`?

**Comment by swinggraphics** [comment]
Yes

**Comment by LukasFritzeDev** [comment]
Could you please provide some detailed information like logs produced when using the `-vv` flag?

**Comment by swinggraphics** [comment]
The only relevant line is the error. Everything else is authentication.

````
* Initialized password authentication                                          
* Authentication complete
* Sending quote commands                                                       
* Could not open directory for reading: No such file or directory
* Connection #0 to host xxx.xxx.xxx.xxx left intact                             
curl: (78) Could not open directory for reading: No such file or directory
````
And again, it does actually create the directory on the server before exiting.

**Comment by swinggraphics** [comment]
When running a second time, it gives a slightly different error the second (fourth) time through:
````
* Authentication complete
* Sending quote commands                                                       
* mkdir command failed: Operation failed
* Connection #0 to host xxx.xxx.xxx.xxx left intact
curl: (21) mkdir command failed: Operation failed
````
Full dump: https://pastebin.com/yWe2zfY0

**Comment by LukasFritzeDev** [comment]
Maybe the path is a Problem. On some hosts using FTP you’ll be in your `www` directory but using ssh you are in the users `$HOME` directory. You can check this by logging in to ssh and list the directory content or using `pwd` to get the current directory. 

If this is the case you could try to set a symlink to your `public_html` or just use the absolute path to the directory.

**Comment by swinggraphics** [comment]
I wondered if the path might be the issue and checked it by logging in  manually.
````
Connected to xxx.xxx.xxx.xxx.
sftp> pwd
Remote working directory: /home1/ktest
sftp> ls
access-logs  etc          logs         mail         perl5        public_ftp   
public_html  ssl          tmp          www
```
The setting in config matches: `url = sftp://xxx.xxx.xxx.xxx/public_html/wp-content/themes/test2/`

And of course, git-ftp does create the directory in the correct place if it does not already exist, so it can't be the path, right?

**Comment by LukasFritzeDev** [comment]
Hm. Should work. Nevertheless, could you try the absolute path?

```
/home1/ktest/public_html/wp-content/themes/test2
```

**Comment by swinggraphics** [comment]
Oh! It does work if I specify the absolute path with `remote-root`!
