### ISSUE TITLE
Run command after pushing

### ISSUE THREAD

**Issue by Sofianio** [git-ftp/git-ftp#500]
### Enhancement

It'd be helpful to have git-ftp run a command (on server) after pushing,
use case: 
- push changes to server
- run migrate (for DB)
- run cache clear

**Comment by mkllnk** [comment]
That would be nice. But the FTP protocol is a File Transfer Protocol only. It doesn't support remote code execution. However, if you have other means to execute code on the server, you can use [hooks](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#hooks-experimental) to execute your own script locally.

If you have SSH access, I wouldn't recommend using Git-ftp. I would use Git push deployments with remote hooks: https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa

I'm closing this issue because the feature is out of Git-ftp's scope.

**Comment by Sofianio** [comment]
True, thanks.
