### ISSUE TITLE
Submodules with ssh-keys

### ISSUE THREAD

**Issue by DerTanzschuh** [git-ftp/git-ftp#507]
### Enhancement: implement submodule handling with ssh-keys

At the moment submodule handling routine ignores ssh-keys. Instead it always uses `--user` and `--passwd`, even if `passwd` is not set.

https://github.com/git-ftp/git-ftp/blob/93131e9987b094386c845c50ec821f61baea8785/git-ftp#L820-L822

This could be improved by adding a if-statement similar to the one in `handle_remote_protocol_options()`:

https://github.com/git-ftp/git-ftp/blob/93131e9987b094386c845c50ec821f61baea8785/git-ftp#L850-L860

**Comment by mkllnk** [comment]
I have been thinking about another solution. Instead of recursively calling git-ftp with all it's parameters we could try to deal with submodules within the same process or possibly fork to child-processes. That way we don't need to generate all the parameters which doesn't scale and is error-prone.

**Comment by mkllnk** [comment]
Exactly, that's why I haven't done it yet. And I haven't had much time for it lately. I would be very happy about your quick fix and you are welcome to work on more issues, for example finding a Travis compatible lftp binary.

**Comment by DerTanzschuh** [comment]
Ok. I’ll create a pull request for this in a moment. 
I would suggest creating a new issue for the complete rewriting of the submodule handling. Maybe we can add this to a 2.0 milestone.
