### ISSUE TITLE
Encodage UTF-8

### ISSUE THREAD

**Issue by ArmandArthur** [git-ftp/git-ftp#552]
Hello, how force the encodage of files to UTF8?

Git-ftp commands change the encodage... Please ?

**Comment by LukasFritzeDev** [comment]
Sorry for the late answer. I needed some time to test it.

In my case the files are uploaded with the correct encoding. Even if I have different file encodings (some in utf-8, some in other ones) the encodings on the server are the same as local. I’ve tested this with two different remote servers.

So unfortunately I can't debug this issue.

What’s your local OS? What’s the one on the remote? Wich protocol do you use (ftp, sftp)?

**Comment by ArmandArthur** [comment]
local OS windows (git BASH), remote OS debian, protocol ftp

I can't reproduce the bug because it's break my application.

**Comment by LukasFritzeDev** [comment]
Sorry for asking, but how do you know the uploading is the issue and the files are on the server with the wrong encoding?

I only ask because there are many locations where the encoding can break. HTTP-Headers, your Apache Web Server, the content from database, even the clients browser. It only shows the application correctly if every part of the stack is using the same encoding. 

So does it make a difference if you upload the files manually with a other ftp client like FileZilla or similar?
