### ISSUE TITLE
Branch doesn't sync after push

### ISSUE THREAD

**Issue by kuroiokami** [git-ftp/git-ftp#554]
Have maybe an issue ? or maybe a misunderstanding.

1. I'm running git-ftp from bitbucket pipelines.
2. I have the repo initialized on a server with our dev branch. 
3. As pipelines runs it's doing a git-ftp push of the latest commit from a feature branch.
4. When I go into the target repo, the files have changed but running a git branch shows that it is still in the dev branch.

Is there a way to make sure the target branch + files ends up the same after the push?

Due to some heavy hitting app linters, we are telling our pipeline to deploy it's working branch to a separate server to run the linter. Just want to make sure the branch in pipelines is totally synced up to the code on the separate server.

**Comment by LukasFritzeDev** [comment]
Git ftp just uploads the files of the currently checked out branch. You don’t need a git repo on your ftp server.

Git-ftp stores the state on the server on a small .git-ftp.log file that contains the current commit hash. The .git directory is never uploaded – for good reason – so the git history and branches and stuff are not saved to the server. The check which files to upload is done using the local repository.

If you want to have a complete git repository (with history and branches) you should probably use a regular remote repo with `git pull`. If you just want to have specific state on the server `git-ftp` is the right tool for you.

Does that answer your question?

**Comment by kuroiokami** [comment]
Hey Lukas,

Thanks Lukas. I guess my question now is how to best initialize that repo on the remote server (It's a really large repo so doing it in pipelines would take forever). When writing new code we currently feature branch off the dev branch. Would this work to have everything sync'd correctly?

1. Pull down dev branch on local machine
2. Do a git-ftp init to remote machine from local machine with dev branch
3. In our feature brach work in pipelines have it do a git-ftp push

Would that correctly sync the states?

Thanks again!

**Comment by LukasFritzeDev** [comment]
This workflow should work well.

Git-ftp makes a `git diff` between the last pushed commit and the current commit (in your case the commit in your pipeline). If you only change a few files (and don’t make a commit in your pipeline!) only these files will be uploaded. I see no problem there.

Be aware the initial push could take some time, since all files are uploaded. It’s best to exclude everything you don’t need. For example, if you have sass or less files you can exclude them using `.git-ftp-ignore` file. See readme for details, please.

And to see some progress during the execution of the command, I’d recommend using the verbose flags. A progress bar is still on our todo list – sadly.

**Comment by kuroiokami** [comment]
Ok. Would it be better to just do

1. Git pull dev branch in a remote directory
2. Run Git-FTP catch up
3. Push from bitbucket pipelines?

Or would that be unsynced?

**Comment by LukasFritzeDev** [comment]
interesting idea. But this way the `.git` folder would be created on the server, which should be avoided.

But you could upload the current state manually with an other ftp client and do a catchup. This might be a good idea, since the upload could be fast than the initial upload with git-ftp.

**Comment by LukasFritzeDev** [comment]
Have you found a good solution for yourself?
