### ISSUE TITLE
Can I use git-ftp for Jekyll deployment?

### ISSUE THREAD

**Issue by zhandosweb** [git-ftp/git-ftp#559]
Hello! 

Before I will sorry for bad English, I'm still learning. Please, let me ask one question. 

Can I use git-ftp for Jekyll deployment? For example: I store all my Jekyll website files into a Dropbox. 

Then I watch all changes using Git. And can I upload entire site first to my hosting, then in future upload only changed files with git-ftp?

Is it possible, right? For my case, I should watch using Git only my _site folder, right?

Sorru again for bad English. I believe, that you understand me. And thank you for your work!

**Comment by LukasFritzeDev** [comment]
Hey,

I guess there wouldn't be any reason not to. It depends a bit on how you manage your files.

> Then I watch all changes using Git. And can I upload entire site first to my hosting, then in future upload only changed files with git-ftp?

Yeah, that's why we have created git-ftp 😉 use `git ftp init` for the first upload and `git ftp push` for the following uploads.

> I should watch using Git only my _site folder, right?

I would organise my complete Jekyll directory in my git repository and then maybe even ignore the `_site` directory (since it is generated code). You could then use the `git-ftp-include` feature to sync only the pages that have been changed. (See [manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#syncing-untracked-files) for details).

If you don’t want to ignore the `_site` directory for git but track the changes with git, another option would be to use `git-ftp-ignore` to ignore everything but the `_site` directory. (Again check the [manual section](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#ignoring-files-to-be-synced) for details).

May I ask a little counter-question? What is the role of Dropbox in your workflow? Why even use Dropbox if you have a git repository? In my experience, the `.git` directory (used by git to store the history and the changes) causes some trouble if used in a directory synced by Dropbox. So I would recommend not to use git inside a Dropbox.

**Comment by zhandosweb** [comment]
Thank you so much for an answer! 

About Dropbox. I just store my Jekyll site (including dev-files and generated _site folder) in Dropbox. It's a cloud system and safe from losing my files. 

I use git to watch any file changes. And Dropbox for cloud storing these files. Also, I think possible to use Github private repository for file storing. Do you mean it? 

And about troubles with .git and Dropbox. At this moment, I no found any problems with it.

**Comment by LukasFritzeDev** [comment]
If it works for you to have a git repository in Dropbox, of course you can do it this way. But if I already have a git repository for a project and need to backup the project, I’d setup a remote repository on GitHub, GitLab or Bitbucket to do so. Why not use the Git-Environment?

The Problem we had was Dropbox sometimes did not synced alle files in the .git directory properly, since there were mostly small files with small files with a lot of changes.

**Comment by zhandosweb** [comment]
Thank you, sir, for the advice! Yes, you are right. And now I plan to use Github for cloud file storage. 

I close this issue, there are I no have questions. 

Thank you again for the answers!
