### ISSUE TITLE
Problems getting git-ftp to push _site folder in Jekyll deployment.

### ISSUE THREAD

**Issue by rabbitDumpling** [git-ftp/git-ftp#567]
I have been using git-ftp for a while, but this is my first Jekyll project (https://github.com/rabbitDumpling/be-muse-site) with it. I am trying to get it to push the contents of my _site folder when I build my site, but I seem to be missing something.

My folder structure is currently:
```
gitfolder
|_ _includes
|_ _layouts
|_ _site
|_ assets
|_ src
```

So first thing, I have set the syncroot default to `_site/`. I can confirm it took since looking in my gitconfig, I can see it is there as `syncroot = _site/` .

I have added '_site' to my .gitignore, so this means I must have a `.git-ftp-include` file (from my understanding of the manual). Inside my `.git-ftp-include` I have:
```
_site/*
```

This is because I want it to take everything in `_site` and push it to my specified ftp path. When go ahead and `$ git ftp init` with this set-up, I get a response of `There are no files to sync.` I know my ftp path is correct because it does generate a `.git-ftp.log` file. I just am unsure what I am doing wrong. I'd appreciate any help with this.

**Comment by mkllnk** [comment]
Hi! I see what you are trying to do but I need to mention that git-ftp may not be the best tool for the job. Let's explore that a bit more.

Git-ftp looks at your git history to decide what changed since your last upload and upload only the changed files. But the files you upload are not under version control. That means that it can't tell which files changed in `_site` by looking at the git history.

If you look at the documentation of the [include file](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#syncing-untracked-files) you see two types of include lines. You can always upload everything in `_site` with this line:

```
!_site/
```

Uploading this way doesn't take the git history into account at all. You could use any other program to just upload everything contained in the _site folder.

If you have a one-to-one match between source files and compiled files in _site then you can define them in your include file. I'm not that familiar with Jekyll but imagine something like this:

```
_site/style.css:_assets/style.scss
```

That would mean that style.css is only uploaded when style.scss has been changed. I'm not sure if you can create rules for all files though.

**Comment by rabbitDumpling** [comment]
Thanks for the detailed response @mkllnk . 

I might be able to make rules for a smaller site like this, but I do have bigger projects coming up and that would be an intense undertaking. So if I was tracking changes in my '_site' folder (by removing it from my `.gitignore`), gitftp would work just fine then? Just want to be sure that is the crux of my problem. While I could use other ftp software, I like the convenience of being able to push to both git and gitftp from inside my console.

If I `git init` inside the `_site` folder, and use git ftp in there, would that work? I ask mainly becuase I ignored the _site folder since I was told that it isn't proper to push generated code to git hub, so if I made a local repo for that folder, would that work? Or would it conflict since it is inside another repo?

**Comment by LukasFritzeDev** [comment]
> I was told that it isn't proper to push generated code to git hub

In general I’d totally agree with this. It’s a good idea to avoid having generated code in the repo. But sometimes it is just necessary. If you want to use the benefits of git-ftp (uploading only changed files) but can't write your own rules, you have to track the files by git somehow. Either by just including them in your regular repo or …

> If I git init inside the _site folder, and use git ftp in there, would that work? […] if I made a local repo for that folder, would that work? Or would it conflict since it is inside another repo?

I had the same idea. Since the directory is ignored by your main repository, It should work well. Then you would have a working repository and a release repository, so to speak. At least you could try it. If it does not work as expect, just delete the `.git` dir inside your `_site` dir.

If you do so you have to make an additional commit, to track the changes in the release repo, but this shouldn’t be a huge drawback. If you want to, you could even automate this using git hooks, but this is another topic.

---

Otherwise there is still the option to just upload everything in your `_site` dir each time you call `git-ftp push`. If the files are quite small and you just don’t want to leave your terminal. But there are other tools that can do the same and even better. If you have ssh-access to your server, you could use `scp` or `rsync` to do so. `rsync` can upload only changed files by comparing meta data. And with a custom alias this can be pretty handy to.

**Comment by rabbitDumpling** [comment]
Since I am trying to find a solution for both this and future projects (which may be drastically bigger), I think I might go with making a secondary git repo in the `_site` folder. It won't be much more to simply commit changes after I build in jekyll and use git ftp from inside the `_site` folder. The bonus is I will have a history of releases in that repo.

Thanks again for all the assistance and advice, it is very much appreciated, and thank you for such an amazing tool you've created in git ftp.
