### ISSUE TITLE
git-ftp-include deletes instead of pushing

### ISSUE THREAD

**Issue by quentincaffeino** [git-ftp/git-ftp#574]
I have a normal node dev environment where you have sources and you have some build folder with compiled code.
For my project those are: `public/css` and `public/js`. Those folders are ignored in `.gitignore`. If I add them to `.git-ftp-include` and run `git ftp push --syncroot public/`, it buffers them for delete and then deletes from ftp server.
I tried this with apt version of the package and 1.6.0 version cloned from git.

.gitignore:

```.gitignore
public/js/*
public/css/*
```

.git-ftp-include:

```.gitignore
!js/**/*
!css/**/*
```

Output from CICD:

```bash
 $ yarn build
	... build stuff ...
 $ tree -h ./public
 ./public
 |-- [4.0K]  css
 |   |-- [ 957]  components.css
 |   `-- [104K]  vendor.css
 |-- [3.1K]  favicon.png
 |-- [ 677]  index.html
 |-- [4.0K]  js
 |   |-- [4.0K]  module
 |   |   |-- [9.8K]  main.js
 |   |   `-- [979K]  vendor.js
 |   `-- [4.0K]  nomodule
 |       |-- [9.9K]  main.js
 |       `-- [984K]  vendor.js
 `-- [ 91K]  visualizer.html
 4 directories, 9 files
 $ git ftp push --syncroot public/
 js/**/*
 css/**/*
 2 files to sync:
 [1 of 2] Buffered for delete 'css/**/*'.
 [2 of 2] Buffered for delete 'js/**/*'.
 Deleting ...
 Last deployment changed from a to b.
```

**Comment by quentincaffeino** [comment]
Sorry, I might be wrong since this repo isn't a generic ftp tool but a tool for synchronizing git projects using ftp. If this is intended behavior fill free to close this issue.
Great project, thanks!

**Comment by LukasFritzeDev** [comment]
Hey, sorry for the delayed answer.

The reason this does not work is that your syntax in `git-ftp-include` is slightly wrong. What you are saying to do is to sync every file in the dir `css`. Aside from the fact that this directory doe’s not exist (should be `public/css` … yes it’s a bit confusing because of sync root), git-ftp can't find any files known by git under this path (remember, we’re looking for files themselves) and therefore tries to always delete the files, cause that's what you told: always sync the state for all these files.

What you can do is say: **Always sync the complete directory**. Just omit the `/**/*` and only use the directory path.

I just made some tests and this should work as you want:
```
!public/js
!public/css
```

---

But even if this works, it will always upload all the files in the directories so there is no benefit in using git-ftp instead of a basic ftp client. What you could do is use a more detailed `.git-ftp-include` definition to upload the files only if the corresponding source files changed. Could look like this:

```
public/css/components.css:scss/components.scss
...
public/js/module/main.js:module.main.ts     // assuming using typescript
public/node_modules:yarn.lock                    // this will upload the node modules only if some dependencies changed
```

More details in the [manual](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#syncing-untracked-files).

Yes this might be some work to setup, but than you can use the power of git.

Hope this helps.

**Comment by quentincaffeino** [comment]
Thanks for your help, I might try it again. For now I switched to `wput`.

---

Detailed is not always an option because when using bundlers it often looks like single file is an input file for a bundler which includes all other files your project needs forming a kind of "tree".
So css dependency tree could look something like this:

```
app.css
|-components.css
|- ...
`-tables.css
```

And the output of a bundler would be simply completly new `app.css` which include all code from other files. So it would be pain to list all those css files in a detailed form. Unless you can use globs with detailed approach to tell include all `/**/*.css`. (Docs doesn't say you can use globs)

---

Another problem could be code splitting. Using code splitting in the end you get more than one file based on your setup. It might split code per-page, per-bundle, ...

While per bundle splitting is ok, usually there are only a few output files which you could list manually in your `.git-ftp-include`. But with per-page splitting this can become a nightmare without globs.

Thanks again, this project is very helpful.

**Comment by LukasFritzeDev** [comment]
As I said, its a bit of work. The `git-ftp-include` i use in some of my front end projects looks something like this:

```
## Upload stylesheet on changes of scss files

style.css:scss/_blocks.scss
style.css:scss/_content.scss
style.css:scss/_fonts.scss
style.css:scss/_footer.scss
style.css:scss/_general.scss
style.css:scss/_header.scss
style.css:scss/_media.scss
style.css:scss/_mixins.scss
style.css:scss/_navigation.scss
style.css:scss/_sidebar.scss
style.css:scss/_typography.scss
style.css:scss/_utilities.scss
style.css:scss/_widgets.scss
style.css:scss/variables.scss
style.css:scss/style.scss
style.css:scss/fullscreen/custom.scss
style.css:scss/fullscreen/variables.scss

css/style-editor.css:scss/_blocks.scss
css/style-editor.css:scss/_content.scss
css/style-editor.css:scss/_fonts.scss
css/style-editor.css:scss/_media.scss
css/style-editor.css:scss/_mixins.scss
css/style-editor.css:scss/_typography.scss
css/style-editor.css:scss/_utilities.scss
css/style-editor.css:scss/variables.scss
css/style-editor.css:scss/style-editor.scss

## Upload minified script files
...
```

As you can see, its possible to specify more than one file that triggers another file to upload. The other way is possible as well:

```
part1.js:bundle.js
part2.js:bundle.js
```

But of course you're right, it would be much nicer with a pattern. We have an issue for this #325. But unfortunately we have little time to implement the many ideas. If you want to contribute you’re very welcome 🙂
