### ISSUE TITLE
It would be good if git ftp shows the uploading information in default.

### ISSUE THREAD

**Issue by bedus-creation** [git-ftp/git-ftp#582]
I know there is option to see the status with **-v** but It would be better if it is in default. Please wanna know what going on inside.

and 

can't we improve the status by showing % of uploading or number of files that are uploaded into the server by default.

**Comment by LukasFritzeDev** [comment]
Yes. We have this in our backlog, #167 but unfortunately we currently don’t have the time to implement this. 

If you would like to help, we are happy to se a pull request, or you could catch up the incomplete one that already exists. 

I’ll close this issue since it’s a duplicate. It’s better to track everything on one issue.
