### ISSUE TITLE
Incorrect .git-ftp-include behaviour - files are not uploaded "always like documentations says

### ISSUE THREAD

**Issue by ivandjuricic** [git-ftp/git-ftp#593]
### Bug (possibly)

* How to reproduce the issue?
1) Have a .gitignore directory eg. `public`
2) add `!public/` to `.git-ftp-include`
3) `git ftp init`  -> files are uploaded allright
4) `git ftp push` -> Everything up-to-date.

Expected behavior (in my humble opinion): push the files specified with `!` from the .git-ftp-include always although there are no new commits

Actual result:
`No changed files for ****. Everything up-to-date.`

The documentation states that `If you have a file that should always be uploaded` you should put it in .git-ftp-include with exclamation mark, so I feel this is misleading. 

Everything works with `git ftp push -a` but I still feel this is not the behaviour that is expected when you go through manual

**Comment by LukasFritzeDev** [comment]
Oh. Maybe the description is a bit misleading. The files are only uploaded if a commit was made to upload. So if you only change git-ignored files (or no files at all) you do not make a commit and therefor git-ftp says "everything up to date". 

I think it's reasonable since in general you only want to upload if something has changed at all. And sincere use git check if something has changed … no new commit = no changes = no need to upload

**Comment by ivandjuricic** [comment]
@LukasFritzeDev makes sense. I just wanted to check if that is expected behaviour
