### ISSUE TITLE
Apple Silicon (M1) support?

### ISSUE THREAD

**Issue by michaelfanta** [git-ftp/git-ftp#599]
Hello to everybody,

I would like to ask if there is any support for Apple Silicon (M1) processors.

Or do you have no experience with installation? My installation always fails with the unnecessary "ghc" package, which is not supported by M1 processors.

Thank you for any response.
Enjoy the rest of your day.

**Comment by mkllnk** [comment]
Hello. I think ghc is only used to produce the documentation (man file). The main script just needs bash and curl. So if you get those two binaries, you can just copy the git-ftp script without any compilation.

**Comment by michaelfanta** [comment]
And can't you please advise me how to do it?

I run the installation via "brew install --build-from-source git-ftp", because classically it cannot be completed via "brew install git-ftp".

Installation via "brew install --build-from-source git-ftp" will end with error:

> Installing dependencies for git-ftp: ghc@8.8, ghc, cabal-install, pandoc and libssh2
ghc@8.8: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.

I'm new to macOS, Windows is relatively easy to install, but I need it to work on my MacBook.

Thank you for any response.
Enjoy the rest of your day.

**Comment by LukasFritzeDev** [comment]
Just stick to [installation steps for using direct download](https://github.com/git-ftp/git-ftp/blob/master/INSTALL.md#linuxunix-based-systems-using-direct-download).

We use `/bin` as the installation location there. I’d recommend `/usr/local/bin` or `/usr/bin`, because `/bin` should be reserved for OS scripts. Just make sure the location is in your [$path variable](https://en.wikipedia.org/wiki/PATH_(variable)#Unix_and_Unix-like), so the script will be found by bash/zsh.

**Comment by michaelfanta** [comment]
Thank you all very much,
but quite complicated for me at the moment, so I chose a solution for now using the GitFTP-Deploy tool:

https://gitftp-deploy.com/

For the moment, it serves a purpose. Perhaps support for the missing libraries will soon open for M1 as well.

Once again, I would like to thank you all for your help.

Good luck to everyone :)
