### ISSUE TITLE
"Unknown SHA1 object" when trying to push "only changed"

### ISSUE THREAD

**Issue by ecxod** [git-ftp/git-ftp#609]
# My problem :

After a lot of try and error, I somehow uploaded the branch development files to the ftp server using git ftp init and the -f option. 
After this I was able to push  with "-a"

I try to upload only the changed files of the branch development, but i get strangely 

```
git ftp push -u "$user" -p "$pass" sftp://example.com:22 --remote-root $path --changed-only -vv -b development
```

### for some reason I can not understand  what is happening ... look what I read in the log files!

```
  git ftp push -u "$user" -p "$pass" sftp://***:22  --remote-root $path --changed-only -vv -b development
  shell: /usr/bin/bash -e {0}
  env:
    server: ***
    user: ***
    pass: ***
    path: /www/htdocs/dev/

*   Trying some_ip:22...
Tue Apr  6 11:08:48 UTC 2021: git-ftp version 1.6.0 running on Linux fv-az224-215 5.4.0-1043-azure #45-Ubuntu SMP Fri Mar 19 17:33:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* TCP_NODELAY set                                                                      
Tue Apr  6 11:08:48 UTC 2021: Downloading only changed files.
* Connected to *** (some_ip) port 22 (#0)
Tue Apr  6 11:08:48 UTC 2021: Syncroot is './'.
##O#- #                                                                       
Tue Apr  6 11:08:48 UTC 2021: currently on branch development
* User: ***
Tue Apr  6 11:08:48 UTC 2021: Checkout on branch development
Tue Apr  6 11:08:48 UTC 2021: Host is '***:22'.
Tue Apr  6 11:08:48 UTC 2021: User is '***'.
Tue Apr  6 11:08:48 UTC 2021: Password is set.
Tue Apr  6 11:08:48 UTC 2021: Path is '/www/htdocs/dev/'.
Tue Apr  6 11:08:48 UTC 2021: The remote sha1 is saved in file '.git-ftp.log'.
Tue Apr  6 11:08:48 UTC 2021: Check if curl is functional.
Tue Apr  6 11:08:48 UTC 2021: Retrieving last commit from ***:22//www/htdocs/dev/.
##O=#  #                                                                      
#=#=-#  #                                                                     
-#O#- #   #                                                                   
-=#=#   #   #                                                                 
* Authentication using SSH public key file
-=O#- #  #    #                                                               
-=O=#  #   #   #                                                              
* Completed password authentication
* Authentication complete
-=O=-#  #    #   #                                                            
{ [41 bytes data]

######################################################################## 100.0%* Connection #0 to host *** left intact

Tue Apr  6 11:08:51 UTC 2021: Last deployed SHA1 for ***:22//www/htdocs/dev/ is ff0558147ca97a3f09f12345f771fa4989e218cc.
Tue Apr  6 11:08:51 UTC 2021: Unknown SHA1 object, make sure you are deploying the right branch and it is up-to-date.
Do you want to ignore and upload all files again? [y/N]: Tue Apr  6 11:08:51 UTC 2021: Aborting...
Error: Process completed with exit code 2.

```

### why does it say **"Unknown SHA1 object"** because some rows up there it says that it is saved to **git-ftp.log** ?
And the information that it was saved to the file it right. The SHA is in there.

Do you understand what is going on ?

**Comment by LukasFritzeDev** [comment]
The flag `--changed-only` is only used for the mirror operation, which is not the case here, so you can omit this option here. By default Git-ftp will push only changed files, since this is the main use case for this tool.

And since you are already on the branch `development` (ie. by calling `git checkout development`) you can omit the flag `-b` as well.

So. What is going on here?
- Git-ftp tries to find out what the last commit is, that was uploaded to the server. To do this the file `.git-ftp.log` is downloaded. It’s content is the commit hash used for the last upload (`ff0558147...`).
- The Git-ftp tries to find the changed files between your current commit and the commit with this hash. The command `git diff` is used for this operation (see [git-ftp#L715](https://github.com/git-ftp/git-ftp/blob/master/git-ftp#L715)).
- This returns an error since the commit with the hash can not be found. This might have various reasons. You might have altered your commit history using `--amend` or `rebase` or you might have [shallow clone](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) (often the case in pipelines (see #543, #515))

Using `-a` the upload is working, since Git-ftp is not checking for changed files but simply takes every files known by git (or included by `.git-ftp-include`).
