### ISSUE TITLE
Better docs/explanation for .git-ftp-ignore syntax

### ISSUE THREAD

**Issue by UltCombo** [git-ftp/git-ftp#80]
The current [`.git-ftp-ignore` docs](https://github.com/git-ftp/git-ftp/blob/develop/man/git-ftp.1.md#ignoring-files-to-be-synced) only has examples, explaining very little about the syntax.

The syntax seems to be newline-separated regular expressions, but the `^` and `$` anchors do not work ([related issue](https://github.com/git-ftp/git-ftp/issues/25)), plus the docs claim that `.*` does not match a directory separator.

It would be nice to have some explanation or at least an example of what the `.git-ftp-tmp` file looks like in addition to a link to the `grep -f` docs in order to explain the [.git-ftp-ignore handling](https://github.com/git-ftp/git-ftp/blob/becf87ac456e30bb4e4bfe1cbce18a5b6078b0ab/git-ftp#L572-L573).

**Comment by mkllnk** [comment]
@UltCombo I took your idea of removing the file status before running `grep`. Actually, that simplifies other code parts as well. Thanks a lot for bringing that up.

I just updated the docs as well.

I still think that it would be easier for people to write shell glob patterns than regular expressions. Especially because `.gitignore` uses shell globs as well. The implementation would probably be a bit slower (http://stackoverflow.com/q/27683656/3377535). What do you think?

**Comment by UltCombo** [comment]
> I still think that it would be easier for people to write shell glob patterns than regular expressions. Especially because .gitignore uses shell globs as well. The implementation would probably be a bit slower (http://stackoverflow.com/q/27683656/3377535). What do you think?

Agreed, glob patterns would make more sense in my opinion too. :smiley:

**Comment by resmo** [comment]
+1 for shell glob patterns from my side. I guess we can ignore the performance concerns in this case.
